name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'Dockerfile'

permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/aio-build:latest
    needs: shellcheck
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create pack
        run: |
          chmod +x ./build.sh
          ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          compression-level: 0
          name: evaron-aio-artifact
          path: "./Evaron-AIO.zip"
