name: Build jobs

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/aio-build:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create pack
        run: |
          chmod +x ./build.sh
          ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          compression-level: 0
          name: evaron-aio-artifact
          path: |
            ./Evaron-AIO.zip
            ./Ultrahand-packages.zip
