name: Create release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

concurrency:
  group: "release"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create pack
        run: chmod +x ./build.sh;./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          compression-level: 0
          name: evaron-aio-artifact
          path: "./Evaron-AIO.zip"

  create-release:
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository_owner }}/aio-build:latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: evaron-aio-artifact
          path: "./"
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./Evaron-AIO.zip"
          bodyFile: "./CHANGELOG.md"
